[package]
edition = "2021"
name = "bevy-racer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_ecs_ldtk = {version = "0.3", features = ["atlas"]}
